name: Build GraphBLAS C++ Specification
on: [push]
permissions:
  contents: write
jobs:
  Build-GraphBLAS-Spec:
    runs-on: ubuntu-latest
    container:
      image: benbrock/graphblas-cpp:build-docs-0.2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build spec
        run: |
          cd $GITHUB_WORKSPACE/markdown
          make
          mkdir graphblas-cpp-spec
          cp graphblas.pdf graphblas-cpp-spec
          cp graphblas.html graphblas-cpp-spec
          mkdir github-pages
          cp graphblas.html github-pages/index.html
      - name: Check on spec
        run: ls $GITHUB_WORKSPACE/markdown
      - name: Archive GraphBLAS C++ Spec
        uses: actions/upload-artifact@v2
        with:
          name: graphblas-cpp-spec
          path: |
            ${{ github.workspace }}/markdown/graphblas-cpp-spec
      - name: Archive GitHub Pages
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: |
            ${{ github.workspace }}/markdown/github-pages
  Deploy-GitHub-Pages:
    needs: Build-GraphBLAS-Spec
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
